In [3]:
import numpy as np

a = np.array([0,1,2,3,4])

a

array([0, 1, 2, 3, 4])

In [9]:
import numpy as np

a = np.array([[0,1,2,3], [5,6,7,8]])

a.ndim 
a.shape

(2, 4)

In [12]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
import numpy as np
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [19]:
import numpy as np
a = np.ones((3,3))
b = np.zeros((3,3))
a
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
import numpy as np
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
import numpy as np
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
import numpy as np
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
import numpy as np
a = np.array([1++2j, 2+4j])
a.dtype

dtype('complex128')

In [25]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [27]:
import numpy as np
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [28]:
import numpy as np
a = np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [29]:
import numpy as np
a = np.diag([1,2,3,4])
a*a

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 16]])

In [30]:
import numpy as np
a = np.array([1,1,0,0],dtype=bool)
b = np.array([0,0,1,1],dtype=bool)

np.logical_or(a,b)

array([ True,  True,  True,  True])

In [31]:
import numpy as np
a = np.array([1,1,0,0],dtype=bool)
b = np.array([0,0,1,1],dtype=bool)

np.logical_and(a,b)

array([False, False, False, False])

In [36]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
a.sum(axis=0)

array([ 6,  8, 10, 12])

In [40]:
import numpy as np
a = np.array([1,2,3,4])
a.min() #to find min
a.max() #to find max
a.argmax() #index of max

3

In [41]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
a.ravel() #2-d to 1-d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
a.T #transponse

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [43]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape

(2, 4)

In [44]:
b = a.ravel()

In [45]:
b=b.reshape((2,4)) #Shape of matrix
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
import numpy as np
a = np.array([[5,8,7],[1,4,3]])
b = np.sort(a,axis=1) #axis=1 means row wise sorting
b

array([[5, 7, 8],
       [1, 3, 4]])

In [48]:
import numpy as np
a = np.array([1,2,3,4])
j_min = a.min() #to find min
j_max = a.max() #to find max
j_max,j_min #index of max

(4, 1)